allowBuilds:
  "@swc/core": false
  esbuild: true
  lefthook: true
  unrs-resolver: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@types/react@19.2.16"
  - react-dom@19.2.7
  - react@19.2.7
  - "@storybook/addon-a11y@10.4.2"
  - "@storybook/addon-docs@10.4.2"
  - "@storybook/addon-vitest@10.4.2"
  - "@storybook/builder-vite@10.4.2"
  - "@storybook/csf-plugin@10.4.2"
  - "@storybook/react-dom-shim@10.4.2"
  - "@storybook/react-vite@10.4.2"
  - "@storybook/react@10.4.2"
  - storybook@10.4.2
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
