export const overlayClassNames = {
  actions: "mbu-overlay-actions",
  aux: "mbu-overlay-aux",
  auxSummary: "mbu-overlay-aux-summary",
  body: "mbu-overlay-body",
  bodyActions: "mbu-overlay-body-actions",
  chip: "mbu-overlay-chip",
  chat: "mbu-overlay-chat",
  chatInputRow: "mbu-overlay-chat-input-row",
  chatMessage: (role: "assistant" | "user") =>
    `mbu-overlay-chat-message mbu-overlay-chat-message--${role}`,
  chatMessages: "mbu-overlay-chat-messages",
  chatRole: "mbu-overlay-chat-role",
  chatScrollerButton: "mbu-overlay-chat-scroller-button",
  chatScrollerItem: "mbu-overlay-chat-scroller-item",
  chatScrollerRoot: "mbu-overlay-chat-scroller",
  chatScrollerSpacer: "mbu-overlay-chat-scroller-spacer",
  chatScrollerViewport: "mbu-overlay-chat-scroller-viewport",
  eventTable: "mbu-overlay-event-table",
  header: "mbu-overlay-header",
  headerLeft: "mbu-overlay-header-left",
  panel: "mbu-overlay-panel",
  popover: "mbu-overlay-popover",
  popoverContent: "mbu-overlay-popover-content",
  popoverText: "mbu-overlay-popover-text",
  popoverTitle: "mbu-overlay-popover-title",
  primaryBlock: "mbu-overlay-primary-block",
  primaryBlockCopy: "mbu-overlay-primary-block--copy",
  primaryMarkdown: "mbu-overlay-primary-markdown",
  quote: "mbu-overlay-quote",
  status: "mbu-overlay-status",
  surface: "mbu-overlay-surface",
  title: "mbu-overlay-title",
} as const;
